### ISSUE TITLE
Question for GS generation

### ISSUE THREAD

**Issue by SYSUykLin** [city-super/Scaffold-GS#16]
Did u use the adaptive strategy in the original GS paper(clone and split)?
Thanks

**Comment by inspirelt** [comment]
Hi, we did not use the split&clone, because it does not match well with our anchor-based settings. Thus we proposed new adaptive growing&pruning strategies to better cope with the anchor-based method.

**Comment by SYSUykLin** [comment]
Thanks for your reply. Another question, SFM provides many initialized points, just a little points treat as anchor points, What to do with the rest points?

**Comment by SYSUykLin** [comment]
And how to define the k in the anchor points? 
![image](https://github.com/city-super/Scaffold-GS/assets/34080744/b40e467c-8961-4028-8d3a-22bc6d632be5)

**Comment by inspirelt** [comment]
The sfm points are processed by voxelization and unique operation, and we choose the voxel center as the anchor (rather than one of the the original points). Points located in the same voxel will be projected into the same anchor. So, all sfm points participate in the anchor generation, actually. 

And, $k$ is a hyper-parameter, we set it to 10 in all the scenes. According to our experiments, Scaffold-GS is not sensitive to $k$.

**Comment by SYSUykLin** [comment]
I see. Anchor points is not a point, but a group of points.
