### ISSUE TITLE
How are the values for new anchors given during anchor_growing?

### ISSUE THREAD

**Issue by laphisboy** [city-super/Scaffold-GS#22]
I am having a hard time understanding how the parameters for new anchors are given.

From what I have understood, the offsets are initialized as 0's.

But, I cannot understand how the new anchor's features (new_feat) is created.

+ Also, why is new_scaling, new_rotation, new_opacities being created when mlp_cov and mlp_opacity is being used?

**Comment by inspirelt** [comment]
The process is sketched as follows:
![image](https://github.com/city-super/Scaffold-GS/assets/9450147/e0d07527-fb4b-4516-a483-d857b43215ab)

The new anchor’s feature is given by pooling the nearby neural gaussian's anchor's features, as shown in https://github.com/city-super/Scaffold-GS/blob/971b68177a0774fc840a12130360344d2a7ab382/scene/gaussian_model.py#L647

where the ```inverse_indices``` records the mapping from neural gs to its rounded grid location (a potential anchor's localtion), as in https://github.com/city-super/Scaffold-GS/blob/971b68177a0774fc840a12130360344d2a7ab382/scene/gaussian_model.py#L616

The function of ```scatter_max``` is clearly stated in https://github.com/rusty1s/pytorch_scatter. 

And, ```new_scaling, new_rotation, new_opacities``` are assigned to new anchors, rather than neural gs. MLPs are globally shared. Anchor(new_feat, new_scaling, new_rotation, new_opacities, blabla) + global mlps produce neural gs.

Hope the above helps you.

**Comment by laphisboy** [comment]
Thank you for your answer! I undertood how new_feat is being created.

What do you mean by "Anchor(new_feat, new_scaling, new_rotation, new_opacities, blabla) + global mlps"?

Is Anchor(new_rotation) or Anchor(new_opacity) the local rotation and opacity value and the output of mlp_cov or mlp_opacity like an offset to the local attributes? I can't locate where the Anchor(new_rotation, new_opacity) are being used.

**Comment by inspirelt** [comment]
"Anchor(new_feat, new_scaling, new_rotation, new_opacities, blabla) + global mlps" denotes generating neural gaussian's properties. Anchor(new_rotation) is used in the voxel prefilter_voxel. Anchor(new_opacity) is not used now, we keep it for  future's potential calling.

**Comment by laphisboy** [comment]
Thank you :)
