### ISSUE TITLE
Training result has no color

### ISSUE THREAD

**Issue by xiaohulihutu** [city-super/Scaffold-GS#7]
Hi there,

Thank you for the great work.

I was testing with a custom dataset and the result looks super strange. It's all black. Any insight about this?

![img_v3_0261_6ba19182-a114-459d-bf87-4a065f7125eg](https://github.com/city-super/Scaffold-GS/assets/25570249/78293f35-cbc1-4b5a-ab0b-87abc84bc3aa)

Thank you so much

**Comment by inspirelt** [comment]
Hi. The result is very very strange and I've never encountered this before. It seems to be caused by the shortage of points, which can be located through following steps. 
1. check the "Number of points at initialisation";
2. visualize the saved point_cloud.ply file in the log;

If the number looks correct (with an amount of about 1e6~1e7), you can check whether the gap between training views and test views is too large. 

Besides, I would also suggest you to check if the custom data is correct, like the camera pose, image format, an so on. 

Please let me know if the above help resolving your problem.

**Comment by inspirelt** [comment]
The viewer for ours is still in development. You can view the image during training through tensorboard.

**Comment by inspirelt** [comment]
Could you please post the log file ```outputs.log```?

**Comment by xiaohulihutu** [comment]
> Could you please post the log file `outputs.log`?

Then I probably know why, I opened the result file with another viewer. 

Sure I will post the log when I back to seat tomorrow.

**Comment by xiaohulihutu** [comment]
Logs
[outputs.log](https://github.com/city-super/Scaffold-GS/files/13644325/outputs.log)
Render and GT
![00000](https://github.com/city-super/Scaffold-GS/assets/25570249/ffc74218-cb78-416a-b613-ca8095025c49)
![00000](https://github.com/city-super/Scaffold-GS/assets/25570249/28c936b0-3137-4cd8-ac74-265a6f7cca80)

Looks like its my fault by putting the result ply file into wrong renderer. Close the issue now.

**Comment by HuangTY96** [comment]
Hi,
I got the same problem, my result ply in renderer is all black too.
could you please tell me which renderer can render my result ply correctly?
